
exports.seed = function(knex, Promise) {
  return knex.raw('DELETE FROM "progress"; ALTER SEQUENCE progress_id_seq RESTART WITH 61')
    .then(function () {
      const progressions = [{
        id: 1,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 1,
        percentage_correct: 23
      }, {
        id: 2,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 2,
        percentage_correct: 31
      }, {
        id: 3,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 3,
        percentage_correct: 40
      }, {
        id: 4,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 4,
        percentage_correct: 48
      }, {
        id: 5,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 5,
        percentage_correct: 44
      }, {
        id: 6,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 6,
        percentage_correct: 53
      }, {
        id: 7,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 7,
        percentage_correct: 60
      }, {
        id: 8,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 8,
        percentage_correct: 74
      }, {
        id: 9,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 9,
        percentage_correct: 77
      }, {
        id: 10,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 10,
        percentage_correct: 91
      }, {
        id: 11,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 1,
        percentage_correct: 40
      }, {
        id: 12,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 2,
        percentage_correct: 22
      }, {
        id: 13,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 3,
        percentage_correct: 88
      }, {
        id: 14,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 4,
        percentage_correct: 6
      }, {
        id: 15,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 5,
        percentage_correct: 17
      }, {
        id: 16,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 6,
        percentage_correct: 97
      }, {
        id: 17,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 7,
        percentage_correct: 41
      }, {
        id: 18,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 8,
        percentage_correct: 14
      }, {
        id: 19,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 9,
        percentage_correct: 38
      }, {
        id: 20,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 10,
        percentage_correct: 80
      }, {
        id: 21,
        user_id: 1,
        language: 'Spanish',
        mode: 'Single',
        game_number: 1,
        percentage_correct: 50
      }, {
        id: 22,
        user_id: 1,
        language: 'French',
        mode: 'Single',
        game_number: 2,
        percentage_correct: 44
      }, {
        id: 23,
        user_id: 1,
        language: 'French',
        mode: 'Single',
        game_number: 3,
        percentage_correct: 60
      }, {
        id: 24,
        user_id: 1,
        language: 'Spanish',
        mode: 'Single',
        game_number: 4,
        percentage_correct: 66
      }, {
        id: 25,
        user_id: 1,
        language: 'Spanish',
        mode: 'Single',
        game_number: 5,
        percentage_correct: 69
      }, {
        id: 26,
        user_id: 1,
        language: 'Spanish',
        mode: 'Single',
        game_number: 6,
        percentage_correct: 76
      }, {
        id: 27,
        user_id: 1,
        language: 'Spanish',
        mode: 'Single',
        game_number: 7,
        percentage_correct: 83
      }, {
        id: 28,
        user_id: 1,
        language: 'Spanish',
        mode: 'Training',
        game_number: 8,
        percentage_correct: 95
      }, {
        id: 29,
        user_id: 1,
        language: 'Spanish',
        mode: 'Single',
        game_number: 9,
        percentage_correct: 99
      }, {
        id: 30,
        user_id: 1,
        language: 'Spanish',
        mode: 'Training',
        game_number: 10,
        percentage_correct: 100
      }, {
        id: 31,
        user_id: 1,
        language: 'German',
        mode: 'Training',
        game_number: 1,
        percentage_correct: 20
      }, {
        id: 32,
        user_id: 1,
        language: 'German',
        mode: 'Training',
        game_number: 2,
        percentage_correct: 12
      }, {
        id: 33,
        user_id: 1,
        language: 'German',
        mode: 'Training',
        game_number: 3,
        percentage_correct: 17
      }, {
        id: 34,
        user_id: 1,
        language: 'German',
        mode: 'Training',
        game_number: 4,
        percentage_correct: 28
      }, {
        id: 35,
        user_id: 1,
        language: 'German',
        mode: 'Training',
        game_number: 5,
        percentage_correct: 29
      }, {
        id: 36,
        user_id: 1,
        language: 'German',
        mode: 'Training',
        game_number: 6,
        percentage_correct: 38
      }, {
        id: 37,
        user_id: 1,
        language: 'German',
        mode: 'Single',
        game_number: 7,
        percentage_correct: 30
      }, {
        id: 38,
        user_id: 1,
        language: 'German',
        mode: 'Single',
        game_number: 8,
        percentage_correct: 31
      }, {
        id: 39,
        user_id: 1,
        language: 'German',
        mode: 'Training',
        game_number: 9,
        percentage_correct: 38
      }, {
        id: 40,
        user_id: 1,
        language: 'German',
        mode: 'Training',
        game_number: 10,
        percentage_correct: 50
      }, {
        id: 41,
        user_id: 1,
        language: 'Latin',
        mode: 'Training',
        game_number: 1,
        percentage_correct: 18
      }, {
        id: 42,
        user_id: 1,
        language: 'Latin',
        mode: 'Training',
        game_number: 2,
        percentage_correct: 32
      }, {
        id: 43,
        user_id: 1,
        language: 'Latin',
        mode: 'Training',
        game_number: 3,
        percentage_correct: 48
      }, {
        id: 44,
        user_id: 1,
        language: 'Latin',
        mode: 'Training',
        game_number: 4,
        percentage_correct: 78
      }, {
        id: 45,
        user_id: 1,
        language: 'Latin',
        mode: 'Training',
        game_number: 5,
        percentage_correct: 66
      }, {
        id: 46,
        user_id: 1,
        language: 'Latin',
        mode: 'Single',
        game_number: 6,
        percentage_correct: 51
      }, {
        id: 47,
        user_id: 1,
        language: 'Latin',
        mode: 'Single',
        game_number: 7,
        percentage_correct: 44
      }, {
        id: 48,
        user_id: 1,
        language: 'Latin',
        mode: 'Single',
        game_number: 8,
        percentage_correct: 18
      }, {
        id: 49,
        user_id: 1,
        language: 'Latin',
        mode: 'Single',
        game_number: 9,
        percentage_correct: 77
      }, {
        id: 50,
        user_id: 1,
        language: 'Latin',
        mode: 'Single',
        game_number: 10,
        percentage_correct: 54
      }, {
        id: 51,
        user_id: 1,
        language: 'Italian',
        mode: 'Training',
        game_number: 1,
        percentage_correct: 26
      }, {
        id: 52,
        user_id: 1,
        language: 'Italian',
        mode: 'Training',
        game_number: 2,
        percentage_correct: 31
      }, {
        id: 53,
        user_id: 1,
        language: 'Italian',
        mode: 'Training',
        game_number: 3,
        percentage_correct: 37
      }, {
        id: 54,
        user_id: 1,
        language: 'Italian',
        mode: 'Training',
        game_number: 4,
        percentage_correct: 51
      }, {
        id: 55,
        user_id: 1,
        language: 'Italian',
        mode: 'Training',
        game_number: 5,
        percentage_correct: 59
      }, {
        id: 56,
        user_id: 1,
        language: 'Italian',
        mode: 'Single',
        game_number: 6,
        percentage_correct: 33
      }, {
        id: 57,
        user_id: 1,
        language: 'Italian',
        mode: 'Single',
        game_number: 7,
        percentage_correct: 38
      }, {
        id: 58,
        user_id: 1,
        language: 'Italian',
        mode: 'Single',
        game_number: 8,
        percentage_correct: 44
      }, {
        id: 59,
        user_id: 1,
        language: 'Italian',
        mode: 'Single',
        game_number: 9,
        percentage_correct: 55
      }, {
        id: 60,
        user_id: 1,
        language: 'Italian',
        mode: 'Single',
        game_number: 10,
        percentage_correct: 70
      }];
      return knex('progress').insert(progressions);
    });
};
